# -*- coding: utf-8 -*-
# flake8: noqa
#
# isbnlib documentation build configuration file, created by
# sphinx-quickstart on Mon Apr 14 21:43:46 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
3.10.8
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))
3.10.8
# -- General configuration ------------------------------------------------
3.10.8
# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'
3.10.8
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []
3.10.8
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
3.10.8
# The suffix of source filenames.
3.10.8
#   For MARKDOWN see 'https://markdown-publishing-guide.readthedocs.io':
#   1. Uncomment the following snippet.
#   2. Keep conf.py and index.rst, but all other .rst files can
#      be written in markdown and the extension renamed to .md
3.10.8
# from recommonmark.parser import CommonMarkParser
# source_parsers = {
#    '.md': CommonMarkParser,
# }
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'
3.10.8
# The encoding of source files.
# source_encoding = 'utf-8-sig'
3.10.8
# The master toctree document.
master_doc = 'index'
3.10.8
# General information about the project.
project = 'isbnlib'
copyright = '2014-2021, Alexandre Conde'
3.10.8
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '3.10'
# The full version, including alpha/beta/rc tags.
release = '3.10.7'
3.10.8
# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None
3.10.8
# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'
3.10.8
# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']
3.10.8
# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None
3.10.8
# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True
3.10.8
# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True
3.10.8
# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False
3.10.8
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
3.10.8
# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []
3.10.8
# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False
3.10.8
# -- Options for HTML output ----------------------------------------------
3.10.8
# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'default'
3.10.8
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}
3.10.8
# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []
3.10.8
# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None
3.10.8
# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None
3.10.8
# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None
3.10.8
# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = None
3.10.8
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
3.10.8
# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []
3.10.8
# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = '%b %d, %Y'
3.10.8
# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True
3.10.8
# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}
3.10.8
# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}
3.10.8
# If false, no module index is generated.
# html_domain_indices = True
3.10.8
# If false, no index is generated.
# html_use_index = True
3.10.8
# If true, the index is split into individual pages for each letter.
# html_split_index = False
3.10.8
# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True
3.10.8
# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True
3.10.8
# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True
3.10.8
# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''
3.10.8
# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None
3.10.8
# Output file base name for HTML help builder.
htmlhelp_basename = 'isbnlibdoc'
3.10.8
# -- Options for LaTeX output ---------------------------------------------
3.10.8
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #'preamble': '',
}
3.10.8
# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        'index',
        'isbnlib.tex',
        'isbnlib Documentation',
        'Alexandre Conde',
        'manual',
    ),
]
3.10.8
# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None
3.10.8
# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False
3.10.8
# If true, show page references after internal links.
# latex_show_pagerefs = False
3.10.8
# If true, show URL addresses after external links.
# latex_show_urls = False
3.10.8
# Documents to append as an appendix to all manuals.
# latex_appendices = []
3.10.8
# If false, no module index is generated.
# latex_domain_indices = True
3.10.8
# -- Options for manual page output ---------------------------------------
3.10.8
# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(
    'index',
    'isbnlib',
    'isbnlib Documentation',
    ['Alexandre Conde'],
    1,
)]
3.10.8
# If true, show URL addresses after external links.
# man_show_urls = False
3.10.8
# -- Options for Texinfo output -------------------------------------------
3.10.8
# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        'index',
        'isbnlib',
        'isbnlib Documentation',
        'Alexandre Conde',
        'isbnlib',
        'Tools for extracting, cleaning and transforming ISBNs.',
        'Miscellaneous',
    ),
]
3.10.8
# Documents to append as an appendix to all manuals.
# texinfo_appendices = []
# If false, no module index is generated.
# texinfo_domain_indices = True
# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'
# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False
